### ISSUE TITLE
Replace references to `id` in the directory documentation with `hash`

### ISSUE THREAD

**Issue by bendoerr** [aserto-dev/topaz-website#31]
There is no `id` field on the protobuf models however, there is a `hash` field which I am assuming is the `id` that is mentioned as that is how it behaves when used. The documentation needs to be updated to reflect this.

**Comment by ronenh** [comment]
Hello and thanks for reporting the issue. We are working towards retiring the `id` field from objects and types. What you noticed is a version of the protobuf messages that was supposed to be the next minor version (0.21.0) but was mistakenly tagged as 0.20.7. We have since published version 0.20.8 which reverts the change and published v0.21.0 with the next version of the proto models.

To give a bit more color, in the current version objects can be identified either by their `id` which is an internal identifier assigned by the directory (a uuid) or the combination of their type and user-provided key. This duality adds much complexity without much benefit.
Similarly, object types will be identified by their name (instead of either name or id) and relation types will be identified by the combination of their name and the name of the object type on which they can occur.

The `hash` field is used for optimistic concurrency. When calling `SetObject` on an object that already exists in the directory, callers are required to provide the hash value of the object currently stored in the directory to avoid unintentional overwrites.

We are in the process of updating our documentation but in the mean time I would encourage you to avoid relying on the `id` field in order to ensure your code is forward compatible.

We apologize for the confusion and inconvenience caused by the version mixup.

**Comment by bendoerr** [comment]
Gotcha! I think that makes sense. I think what I was running into as well was the undocumented behavior when a session is established vs when a session is not established. I hadn't implemented the session and was running into the issue where to update objects I needed to look up their hash first and provide that which is why I confused it with an ID. It wasn't until later when I was reading the code that I saw the check for if the session was active then assign currHash.
